-- Exact schema matching the user's database screenshot
create table users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  "e-mail" text,
  credits bigint,
  user_id text -- Clerk User ID
);

-- Note: user_id should be unique to prevent duplicates
alter table users add constraint users_user_id_key unique (user_id);
